### ISSUE TITLE
[FEATURE] Picture Controller

### ISSUE THREAD

**Issue by yujinkim1** [BlindOver/blindover_flutter#11]
## Description
- 카메라 프리뷰 화면에서 사용자가 캡쳐 버튼과 상호작용하면 Rest API 서버로 전달할 이미지를 임시 경로에 저장합니다.
- 새로운 이미지가 캡쳐되면 기존에 저장된 이미지를 삭제하고 새로 저장합니다.

## Task

- [x] Add `path_provider` package
- [x] 이미지를 저장할 임시 경로를 가져오는 함수
- [x] 이미지를 임시 경로에 저장하는 함수
- [x] 새로운 이미지가 캡쳐되면 기존의 이미지를 삭제하는 함수

## ETC
```[tasklist]
1. 실제 테스트 장비에서 확인해야합니다.
```
