### ISSUE TITLE
[FEATURE] Camera permission handler

### ISSUE THREAD

**Issue by yujinkim1** [BlindOver/blindover_flutter#3]
## Description
- 최초 애플리케이션 실행 시 카메라 접근 권한을 요청할 수 있도록 합니다.

## Task
- [x] Initial Screen 생성
- [x] 카메라 모듈 의존성 추가
- [x] 카메라 인스턴스
- [x] 카메라 권한 핸들러

## ETC
``````

**Comment by yujinkim1** [comment]
> ## Description
> * 최초 애플리케이션 실행 시 카메라 접근 권한을 요청할 수 있도록 합니다.
> 
> ## Task
> * [x]  Initial Screen 생성
> * [x]  카메라 모듈 의존성 추가
> * [ ]  카메라 인스턴스
> * [ ]  카메라 권한 핸들러
> 
> ## ETC

-  [ ] 앱 생명 주기 처리 `didChangeAppLifeCycleState()`
